var daysofweek = [ "Sun", "Mon", "Tue", "Wed", 
                   "Thu", "Fri", "Sat" ];

var months = [ "January", "February", "March", "April",
               "May", "June", "July", "August", "September",
               "October", "November", "December" ];

var ranknames = {
  "Sd1": "Sunday I Class", 
  "F1": "Privileged Feria I Class", 
  "V1": "Vigil I Class", 
  "D1": "Double I Class",
  "Sd2": "Sunday II Class", 
  "F2": "Privileged Feria II Class", 
  "D2": "Double II Class",
  "Sd": "Semidouble", 
  "V2": "Vigil II Class", 
  "Gd": "Greater Double", 
  "D": "Double", 
  "F3": "Privileged Feria III Class", 
  "V": "Vigil", 
  "S": "Simple", 
  "iv": "Feria",
  "Comm": "Commemoration", 
  "M": "Memorial"
}

var moveable = {
  "The Sunday of Septuagesima": { "basis": "easter", "diff": -63 },
  "The Sunday of Sexagesima": { "basis": "easter", "diff": -56 },
  "The Sunday of Quinquagesima": { "basis": "easter", "diff": -49 },
  "Ash Wednesday": { "basis": "easter", "diff": -46 },
  "Thursday after Ash Wednesday": { "basis": "easter", "diff": -45 },
  "Friday after Ash Wednesday": { "basis": "easter", "diff": -44 },
  "Saturday after Ash Wednesday": { "basis": "easter", "diff": -43 },
  "I Sunday in Lent": { "basis": "easter", "diff": -42 },
  "Monday after Lent I": { "basis": "easter", "diff": -41 },
  "Tuesday after Lent I": { "basis": "easter", "diff": -40 },
  "Ember Wednesday in Lent": { "basis": "easter", "diff": -39 },
  "Thursday after Lent I": { "basis": "easter", "diff": -38 },
  "Ember Friday in Lent": { "basis": "easter", "diff": -37 },
  "Ember Saturday in Lent": { "basis": "easter", "diff": -36 },
  "II Sunday in Lent": { "basis": "easter", "diff": -35 },
  "Monday after Lent II": { "basis": "easter", "diff": -34 },
  "Tuesday after Lent II": { "basis": "easter", "diff": -33 },
  "Wednesday after Lent II": { "basis": "easter", "diff": -32 },
  "Thursday after Lent II": { "basis": "easter", "diff": -31 },
  "Friday after Lent II": { "basis": "easter", "diff": -30 },
  "Saturday after Lent II": { "basis": "easter", "diff": -29 },
  "III Sunday in Lent": { "basis": "easter", "diff": -28 },
  "Monday after Lent III": { "basis": "easter", "diff": -27 },
  "Tuesday after Lent III": { "basis": "easter", "diff": -26 },
  "Wednesday after Lent III": { "basis": "easter", "diff": -25 },
  "Thursday after Lent III": { "basis": "easter", "diff": -24 },
  "Friday after Lent III": { "basis": "easter", "diff": -23 },
  "Saturday after Lent III": { "basis": "easter", "diff": -22 },
  "IV Sunday in Lent": { "basis": "easter", "diff": -21 },
  "Monday after Lent IV": { "basis": "easter", "diff": -20 },
  "Tuesday after Lent IV": { "basis": "easter", "diff": -19 },
  "Wednesday after Lent IV": { "basis": "easter", "diff": -18 },
  "Thursday after Lent IV": { "basis": "easter", "diff": -17 },
  "Friday after Lent IV": { "basis": "easter", "diff": -16 },
  "Saturday after Lent IV": { "basis": "easter", "diff": -15 },
  "Sunday of the Passion": { "basis": "easter", "diff": -14 },
  "Monday after Passion Sunday": { "basis": "easter", "diff": -13 },
  "Tuesday after Passion Sunday": { "basis": "easter", "diff": -12 },
  "Wednesday after Passion Sunday": { "basis": "easter", "diff": -11 },
  "Thursday after Passion Sunday": { "basis": "easter", "diff": -10 },
  "Friday after Passion Sunday": { "basis": "easter", "diff": -9 },
  "Saturday after Passion Sunday": { "basis": "easter", "diff": -8 },
  "Palm Sunday": { "basis": "easter", "diff": -7 },
  "Monday in Holy Week": { "basis": "easter", "diff": -6 },
  "Tuesday in Holy Week": { "basis": "easter", "diff": -5 },
  "Wednesday in Holy Week": { "basis": "easter", "diff": -4 },
  "Thursday of the Lord's Supper": { "basis": "easter", "diff": -3 },
  "Friday of the Preparation (Good Friday)": { "basis": "easter", "diff": -2 },
  "Holy Saturday": { "basis": "easter", "diff": -1 },
  "Sunday of the Resurrection (Easter)": { "basis": "easter", "diff": 0 },
  "Monday in the Octave of Easter": { "basis": "easter", "diff": 1 },
  "Tuesday in the Octave of Easter": { "basis": "easter", "diff": 2 },
  "Wednesday in the Octave of Easter": { "basis": "easter", "diff": 3 },
  "Thursday in the Octave of Easter": { "basis": "easter", "diff": 4 },
  "Friday in the Octave of Easter": { "basis": "easter", "diff": 5 },
  "Saturday in the Octave of Easter": { "basis": "easter", "diff": 6 },
  "The Octave of Easter (Dominica in Albis; Low Sunday)": { "basis": "easter", "diff": 7 },
  "II Sunday after Easter": { "basis": "easter", "diff": 14 },
  "III Sunday after Easter": { "basis": "easter", "diff": 21 },
  "IV Sunday after Easter": { "basis": "easter", "diff": 28 },
  "V Sunday after Easter": { "basis": "easter", "diff": 35 },
  "The Ascension of Our Lord": { "basis": "easter", "diff": 39 },
  "Day II within the Octave of the Ascension": { "basis": "easter", "diff": 40 },
  "Day III within the Octave of the Ascension": { "basis": "easter", "diff": 41 },
  "Day IV within the Octave of The Ascension": { "basis": "easter", "diff": 42 },
  "Day V within the Octave of the Ascension": { "basis": "easter", "diff": 43 },
  "Day VI within the Octave of the Ascension": { "basis": "easter", "diff": 44 },
  "Day VII within the Octave of the Ascension": { "basis": "easter", "diff": 45 },
  "The Octave of the Ascension": { "basis": "easter", "diff": 46 },
  "Friday after the Octave of the Ascension": { "basis": "easter", "diff": 47 },
  "The Vigil of Pentecost": { "basis": "easter", "diff": 48 },
  "Pentecost Sunday": { "basis": "easter", "diff": 49 },
  "Monday within the Octave of Pentecost": { "basis": "easter", "diff": 50 },
  "Tuesday within the Octave of Pentecost": { "basis": "easter", "diff": 51 },
  "Ember Wednesday in Pentecost": { "basis": "easter", "diff": 52 },
  "Thursday within the Octave of Pentecost": { "basis": "easter", "diff": 53 },
  "Ember Friday in Pentecost": { "basis": "easter", "diff": 54 },
  "Ember Saturday in Pentecost": { "basis": "easter", "diff": 55 },
  "The Feast of the Most Holy Trinity": { "basis": "easter", "diff": 56 },
  "The Feast of the Most Holy Body of Christ": { "basis": "easter", "diff": 60 },
  "Day II within the Octave of Corpus Christi": { "basis": "easter", "diff": 61 },
  "Day III within the Octave of Corpus Christi": { "basis": "easter", "diff": 62 },
  "Day IV within the Octave of Corpus Christi": { "basis": "easter", "diff": 63 },
  "Day V within the Octave of Corpus Christi": { "basis": "easter", "diff": 64 },
  "Day VI within the Octave of Corpus Christi": { "basis": "easter", "diff": 65 },
  "Day VII within the Octave of Corpus Christi": { "basis": "easter", "diff": 66 },
  "Octave of Corpus Christi": { "basis": "easter", "diff": 67 },
  "Ember Wednesday in September": { "basis": "ember", "diff": 0 },
  "Ember Friday in September": { "basis": "ember", "diff": 2 },
  "Ember Saturday in September": { "basis": "ember", "diff": 3 },
  "I Sunday in Advent": { "basis": "advent", "diff": 0 },
  "II Sunday in Advent": { "basis": "advent", "diff": 7 },
  "III Sunday in Advent": { "basis": "advent", "diff": 14 },
  "Ember Wednesday in Advent": { "basis": "advent", "diff": 17 },
  "Ember Friday in Advent": { "basis": "advent", "diff": 19 },
  "Ember Saturday in Advent": { "basis": "advent", "diff": 20 },
  "IV Sunday in Advent": { "basis": "advent", "diff": 21 },
};


// TODO: If repaste... fix Innocent 7-28, Juvenalis 5-3, Deacons/Martyrs 8-6
var fixed = {
  "The Circumcision of Our Lord": { "m":  1, "d":  1 }, 
  "(Octave Day of the Nativity)": { "m":  1, "d":  1 }, 
  "Most Holy Name of Jesus": { "m":  1, "d":  2 }, 
  "Octave Day of St. Stephen": { "m":  1, "d":  2 }, 
  "Octave Day of St. John, Apostle & Evangelist": { "m":  1, "d":  3 }, 
  "Octave Day of the Holy Innocents": { "m":  1, "d":  4 }, 
  "St. Titus, Bishop & Confessor": { "m":  1, "d":  4 }, 
  "The Vigil of the Epiphany": { "m":  1, "d":  5 }, 
  "St. Telesphorus of Rome, Bishop & Martyr": { "m":  1, "d":  5 }, 
  "The Epiphany of Our Lord": { "m":  1, "d":  6 }, 
  "Day II within the Octave of the Epiphany": { "m":  1, "d":  7 }, 
  "Day III within the Octave of the Epiphany": { "m":  1, "d":  8 }, 
  "Day IV within the Octave of the Epiphany": { "m":  1, "d":  9 }, 
  "Day V within the Octave of the Epiphany": { "m":  1, "d": 10 }, 
  "St. Paul the First Hermit": { "m":  1, "d": 10 }, 
  "Day VI within the Octave of the Epiphany": { "m":  1, "d": 11 }, 
  "St. Hyginus of Rome, Bishop & Martyr": { "m":  1, "d": 11 }, 
  "Day VII within the Octave of the Epiphany": { "m":  1, "d": 12 }, 
  "St. Benedict Biscop, Abbot": { "m":  1, "d": 12 }, 
  "Octave Day of the Epiphany": { "m":  1, "d": 13 }, 
  "(Baptism of Our Lord)": { "m":  1, "d": 13 }, 
  "St. Hilary, Bishop, Confessor & Doctor": { "m":  1, "d": 14 }, 
  "St. Felix of Nola, Priest & Martyr": { "m":  1, "d": 14 }, 
  "St. Maurus, Abbot": { "m":  1, "d": 15 }, 
  "St. Marcellus of Rome, Bishop & Martyr": { "m":  1, "d": 16 }, 
  "St. Anthony, Abbot": { "m":  1, "d": 17 }, 
  "Chair of St. Peter in Rome": { "m":  1, "d": 18 }, 
  "Commemoration of St. Paul": { "m":  1, "d": 18 }, 
  "St. Prisca of Rome, Virgin Martyr": { "m":  1, "d": 18 }, 
  "Ss. Marius, Martha, Audifax, & Abachum, Martyrs": { "m":  1, "d": 19 }, 
  "St. Mark of Ephesus, Bishop & Confessor": { "m":  1, "d": 19 }, 
  "Ss. Fabian (Bishop) & Sebastian, Martyrs": { "m":  1, "d": 20 }, 
  "St. Agnes of Rome, Virgin & Martyr": { "m":  1, "d": 21 }, 
  "Ss. Vincent (Deacon) & Anastasius, Martyrs": { "m":  1, "d": 22 }, 
  "St. Emerentiana, Virgin & Martyr": { "m":  1, "d": 23 }, 
  "St. Timothy, Bishop & Martyr": { "m":  1, "d": 24 }, 
  "The Conversion Of St. Paul The Apostle": { "m":  1, "d": 25 }, 
  "Commemoration of St. Peter": { "m":  1, "d": 25 }, 
  "St. Polycarp of Smyrna, Bishop & Martyr": { "m":  1, "d": 26 }, 
  "St. John Chrysostom, Bishop, Confessor & Doctor": { "m":  1, "d": 27 }, 
  "The Second Feast of St. Agnes, Virgin Martyr": { "m":  1, "d": 28 }, 
  "St. Martina, Virgin & Martyr": { "m":  1, "d": 30 }, 
  "St. Ignatius of Antioch, Bishop & Martyr": { "m":  2, "d":  1 }, 
  "St. Bridget of Ireland, Virgin": { "m":  2, "d":  1 }, 
  "Purification of the B.V.M.": { "m":  2, "d":  2 }, 
  "St. Blaise, Bishop & Martyr": { "m":  2, "d":  3 }, 
  "The New Martyrs of Russia": { "m":  2, "d":  4 }, 
  "St. Joseph of Aleppo, Martyr": { "m":  2, "d":  4 }, 
  "St. Agatha, Virgin & Martyr, Abbot": { "m":  2, "d":  5 }, 
  "St. Photius, Bishop & Confessor": { "m":  2, "d":  6 }, 
  "St. Dorothy, Virgin & Martyr": { "m":  2, "d":  6 }, 
  "St. Romuald, Abbot": { "m":  2, "d":  7 }, 
  "St. Cyril of Alexandria, Bishop, Confessor & Doctor": { "m":  2, "d":  9 }, 
  "St. Apollonia of Alexandria, Virgin & Martyr": { "m":  2, "d":  9 }, 
  "St. Scholastica, Virgin": { "m":  2, "d": 10 }, 
  "St. Gregory II, Bishop & Martyr": { "m":  2, "d": 11 }, 
  "St. Valentine, Priest & Martyr": { "m": 2, "d": 14 },
  "Ss. Faustinus & Jovita, Martyrs": { "m":  2, "d": 15 }, 
  "St. Simeon of Jerusalem, Bishop & Martyr": { "m":  2, "d": 18 }, 
  "Chair of St. Peter at Antioch": { "m":  2, "d": 22 }, 
  "Commemoration of St. Paul": { "m":  2, "d": 22 }, 
  "Vigil of St. Matthias": { "m":  2, "d": 23 }, 
  "St. Matthias, Apostle": { "m":  2, "d": 24 }, 
  "St. Walburga of Heidenheim, Virgin": { "m":  2, "d": 25 }, 
  "St. Raphael of Brooklyn, Bishop & Confessor": { "m":  2, "d": 27 }, 
  "St. Alexander of Alexandria, Bishop & Confessor": { "m":  2, "d": 27 }, 
  "St. David of Wales, Bishop & Confessor": { "m":  3, "d":  1 }, 
  "St. Chad, Bishop & Confessor": { "m":  3, "d":  2 }, 
  "Ss. Perpetua & Felicitas, Martyrs": { "m":  3, "d":  6 }, 
  "St. Gregory of Nyssa, Bishop, Confessor & Doctor": { "m":  3, "d":  9 }, 
  "The Forty Holy Martyrs": { "m":  3, "d": 10 }, 
  "St. Gregory the Great, Bishop, Confessor & Doctor": { "m":  3, "d": 12 }, 
  "St. Patrick, Bishop & Confessor": { "m":  3, "d": 17 }, 
  "St. Joseph of Arimathea, C.": { "m":  3, "d": 17 }, 
  "St. Cyril of Jerusalem, Bishop, Confessor & Doctor": { "m":  3, "d": 18 }, 
  "St. Edward, King & Martyr": { "m":  3, "d": 18 }, 
  "St. Joseph, Spouse of the B.V.M.": { "m":  3, "d": 19 }, 
  "St. Cuthbert, Bishop & Confessor": { "m":  3, "d": 20 }, 
  "St. Benedict, Abbot": { "m":  3, "d": 21 }, 
  "St. Gabriel the Archangel": { "m":  3, "d": 24 }, 
  "The Annunciation of the B.V.M.": { "m":  3, "d": 25 }, 
  "St. John Damascene, Confessor & Doctor": { "m":  3, "d": 27 }, 
  "St. John Climacus, Abbot": { "m":  3, "d": 30 }, 
  "St. Innocent of Alaska, Bishop & Confessor": { "m":  3, "d": 31 }, 
  "St. Isidore of Seville, Bishop, Confessor & Doctor": { "m":  4, "d":  4 }, 
  "St. Tikhon of Moscow, Bishop & Confessor": { "m":  4, "d":  7 }, 
  "Our Lady of Sorrows": { "m":  4, "d":  7 }, 
  "St. Leo the Great, Bishop, Confessor & Doctor": { "m":  4, "d": 11 }, 
  "St. Hermengild, Martyr": { "m":  4, "d": 13 }, 
  "St. Justin, Martyr": { "m":  4, "d": 14 }, 
  "St. Tiburtius, Valerian & Maximus, Martyrs": { "m":  4, "d": 14 }, 
  "St. Anicetus, Bishop & Martyr": { "m":  4, "d": 17 }, 
  "Ss. Soter & Caius, Martyrs": { "m":  4, "d": 22 }, 
  "St. George, Martyr": { "m":  4, "d": 23 }, 
  "Day II within the Octave of St. George": { "m":  4, "d": 24 }, 
  "St. Mark, Evangelist": { "m":  4, "d": 25 }, 
  "Day III within the Octave of St. George": { "m":  4, "d": 25 }, 
  "The Greater Litanies": { "m":  4, "d": 25 }, 
  "Day IV within the Octave of St. George": { "m":  4, "d": 26 }, 
  "St. Cletus & Marcellinus, Martyrs": { "m":  4, "d": 26 }, 
  "Day V within the Octave of St. George": { "m":  4, "d": 27 }, 
  "Day VI within the Octave of St. George": { "m":  4, "d": 28 }, 
  "St. Vitalis, Martyr": { "m":  4, "d": 28 }, 
  "Day VII within the Octave of St. George": { "m":  4, "d": 29 }, 
  "Octave Day of St. George": { "m":  4, "d": 30 }, 
  "Ss. Philip & James, Apostles": { "m":  5, "d":  1 }, 
  "St. Athanasius, Bishop, Confessor & Doctor": { "m":  5, "d":  2 }, 
  "Finding of the Holy Cross": { "m":  5, "d":  3 }, 
  "Solemnity of St. Joseph, Spouse of the B.V.M.": { "m":  5, "d":  3 }, 
  "Ss. Alexander (Bishop), Eventius, Theodulus (Martyrs) & Juvenalis (Bishop & Confessor)": { "m":  5, "d":  3 }, 
  "St. Monica, Widow": { "m":  5, "d":  4 }, 
  "St. John before the Latin Gate": { "m":  5, "d":  6 }, 
  "St. Alexis Toth, Priest & Confessor": { "m":  5, "d":  7 }, 
  "The Apparition of St. Michael the Archangel": { "m":  5, "d":  8 }, 
  "St. Gregory Nazianzen, Bishop, Confessor & Doctor": { "m":  5, "d":  9 }, 
  "Ss. Gordian & Epimachus, Martyrs": { "m":  5, "d": 10 }, 
  "St. Pachomius, Abbot": { "m":  5, "d": 10 }, 
  "Ss. Nereus, Achilles, Domitilla & Pancras, Martyrs": { "m":  5, "d": 12 }, 
  "St. Boniface of Tarsus, Martyr": { "m":  5, "d": 14 }, 
  "St. Venantius, Martyr": { "m":  5, "d": 18 }, 
  "St. Pudentiana, Virgin": { "m":  5, "d": 19 }, 
  "St. Dunstan of Canterbury, Bishop & Confessor": { "m":  5, "d": 19 }, 
  "St. Constantine, Emperor & Confessor": { "m":  5, "d": 21 }, 
  "St. Vincent of Lerins, Confessor": { "m":  5, "d": 24 }, 
  "St. Urban, Bishop & Martyr": { "m":  5, "d": 25 }, 
  "St. Augustine of Canterbury, Bishop & Confessor": { "m":  5, "d": 26 }, 
  "St. Eleutherius, Bishop & Martyr": { "m":  5, "d": 26 }, 
  "St. Bede the Venerable, Confessor & Doctor": { "m":  5, "d": 27 }, 
  "St. John I, Bishop & Martyr": { "m":  5, "d": 27 }, 
  "St. Felix I, Bishop & Martyr": { "m":  5, "d": 30 }, 
  "St. Petronilla, Virgin": { "m":  5, "d": 31 }, 
  "Ss. Marcellinus, Peter & Erasmus, Martyrs": { "m":  6, "d":  2 }, 
  "St. Boniface, Bishop & Martyr": { "m":  6, "d":  5 }, 
  "St. Columba of Iona, Abbot": { "m":  6, "d":  9 }, 
  "Ss. Primus & Felician, Martyrs": { "m":  6, "d":  9 }, 
  "St. Margaret of Scotland, Queen & Widow": { "m":  6, "d": 10 }, 
  "St. Barnabas, Apostle": { "m":  6, "d": 11 }, 
  "Ss. Basilides, Cyrinus, Nabor & Nazarius, Martyrs": { "m":  6, "d": 12 }, 
  "St. Basil the Great, Bishop, Confessor & Doctor": { "m":  6, "d": 14 }, 
  "Ss. Vitus, Modestus & Crescentia, Martyrs": { "m":  6, "d": 15 }, 
  "St. Ephrem the Syrian, Deacon, Confessor & Doctor": { "m":  6, "d": 18 }, 
  "Ss. Mark & Marcellianus, Martyrs": { "m":  6, "d": 18 }, 
  "Ss. Gervase & Protase, Martyrs": { "m":  6, "d": 19 }, 
  "St. Silverius, Bishop & Martyr": { "m":  6, "d": 20 }, 
  "Translation of St. Edward, King & Martyr": { "m":  6, "d": 20 }, 
  "St. Alban, Protomartyr of England": { "m":  6, "d": 22 }, 
  "St. Paulinus, Bishop & Confessor": { "m":  6, "d": 22 }, 
  "Vigil of St. John the Baptist": { "m":  6, "d": 23 }, 
  "St. Etheldreda, Queen & Virgin": { "m":  6, "d": 23 }, 
  "Feast of the Most Sacred Heart of Jesus": { "m":  6, "d": 23 }, 
  "Nativity of St. John the Baptist": { "m":  6, "d": 24 }, 
  "Day II within the Octave of St. John Baptist": { "m":  6, "d": 25 }, 
  "Ss. John & Paul, Martyrs": { "m":  6, "d": 26 }, 
  "Day III within the Octave of St. John Baptist": { "m":  6, "d": 26 }, 
  "Day IV within the Octave of St. John Baptist": { "m":  6, "d": 27 }, 
  "St. Irenæus of Lyons, Bishop & Martyr": { "m":  6, "d": 28 }, 
  "Day V within the Octave of St. John Baptist": { "m":  6, "d": 28 }, 
  "Ss. Peter & Paul, Apostles": { "m":  6, "d": 29 }, 
  "Day VI within the Octave of St. John Baptist": { "m":  6, "d": 29 }, 
  "Commemoration of St. Paul, Apostle": { "m":  6, "d": 30 }, 
  "Commemoration of St. Peter, Apostle": { "m":  6, "d": 30 }, 
  "Day VII within the Octave of St. John Baptist": { "m":  6, "d": 30 }, 
  "Octave of the Most Sacred Heart of Jesus": { "m":  6, "d": 30 }, 
  "Day II within the Octave of Ss. Peter & Paul": { "m":  6, "d":  30 }, 
  "Octave of St. John Baptist": { "m":  7, "d":  1 }, 
  "Day III within the Octave of Ss. Peter & Paul": { "m":  7, "d":  1 }, 
  "Most Precious Blood of Our Lord Jesus Christ": { "m":  7, "d":  1 }, 
  "Visitation of the B.V.M.": { "m":  7, "d":  2 }, 
  "Day IV within the Octave of Ss. Peter & Paul": { "m":  7, "d":  2 }, 
  "St. John of San Francisco, Bishop & Confessor": { "m":  7, "d":  2 }, 
  "Ss. Processus & Martinian, Martyrs": { "m":  7, "d":  2 }, 
  "Day V within the Octave of Ss. Peter & Paul": { "m":  7, "d":  3 }, 
  "St. Leo II, Bishop & Confessor": { "m":  7, "d":  3 }, 
  "Day VI within the Octave of Ss. Peter & Paul": { "m":  7, "d":  4 }, 
  "Day VII within the Octave of Ss. Peter & Paul": { "m":  7, "d":  5 }, 
  "The Octave of Ss. Peter & Paul": { "m":  7, "d":  6 }, 
  "Ss. Cyril and Methodius, Bishops & Confessors": { "m":  7, "d":  7 }, 
  "The Seven Holy Brothers, with Ss. Rufina & Secunda, Martyrs": { "m":  7, "d": 10 }, 
  "St. Joseph of Damascus (Priest) & his companions, Martyrs": { "m":  7, "d": 10 }, 
  "St. Pius I, Bishop & Martyr": { "m":  7, "d": 11 }, 
  "Ss. Nabor & Felix, Martyrs": { "m":  7, "d": 12 }, 
  "St. Anacletus, Bishop & Martyr": { "m":  7, "d": 13 }, 
  "St. Vladimir of Kiev, King & Confessor": { "m":  7, "d": 15 }, 
  "St. Henry, Emperor & Confessor": { "m":  7, "d": 15 }, 
  "Our Lady of Einsiedeln": { "m":  7, "d": 16 }, 
  "St. Alexius, Confessor": { "m":  7, "d": 17 }, 
  "St. Sergius of Radonezh, Abbot": { "m":  7, "d": 18 }, 
  "St. Symphorosa & her seven sons, Martyrs": { "m":  7, "d": 18 }, 
  "St. Seraphim of Sarov, Priest & Confessor": { "m":  7, "d": 19 }, 
  "St. Elias the Prophet": { "m":  7, "d": 20 }, 
  "St. Margaret of Antioch, Virgin & Martyr": { "m":  7, "d": 20 }, 
  "St. Praxedes, Virgin": { "m":  7, "d": 21 }, 
  "St. Mary Magdalene, Penitent": { "m":  7, "d": 22 }, 
  "St. John Cassian, Abbot": { "m":  7, "d": 23 }, 
  "St. Apollinaris of Ravenna, Bishop & Martyr": { "m":  7, "d": 23 }, 
  "St. Liborius, Bishop & Confessor": { "m":  7, "d": 23 }, 
  "Vigil of St. James": { "m":  7, "d": 24 }, 
  "St. Christina, Virgin & Martyr": { "m":  7, "d": 24 }, 
  "St. James, Apostle": { "m":  7, "d": 25 }, 
  "St. Christopher, Martyr": { "m":  7, "d": 25 }, 
  "St. Anne, Mother of the B.V.M.": { "m":  7, "d": 26 }, 
  "St. Pantaleon, Martyr": { "m":  7, "d": 27 }, 
  "Ss. Nazarius, Celsus, Martyrs; St. Victor, Bishop & Martyr; & Innocent, Bishop & Confessor": { "m":  7, "d": 28 }, 
  "St. Martha of Bethany, Virgin": { "m":  7, "d": 29 }, 
  "Ss. Felix II (Bishop), Simplicius, Faustinus & Beatrice, Martryrs": { "m":  7, "d": 29 }, 
  "Ss. Abdon & Sennen, Martyrs": { "m":  7, "d": 30 }, 
  "Chains of St. Peter, Apostle": { "m":  8, "d":  1 }, 
  "Commemoration of St. Paul, Apostle": { "m":  8, "d":  1 }, 
  "Holy Maccabees, Martyrs": { "m":  8, "d":  1 }, 
  "St. Stephen, Bishop & Martyr": { "m":  8, "d":  2 }, 
  "The Finding of St. Stephen, Protomartyr": { "m":  8, "d":  3 }, 
  "Dedication of Our Lady of the Snows": { "m":  8, "d":  5 }, 
  "St. Oswald, King & Martyr": { "m":  8, "d":  5 }, 
  "The Transfiguration of Our Lord Jesus Christ": { "m":  8, "d":  6 }, 
  "Ss. Sixtus II (Bishop & Martyr), Felicissimus & Agapitus (Deacons), Martyrs": { "m":  8, "d":  6 }, 
  "St. Donatus, Bishop & Martyr": { "m":  8, "d":  7 }, 
  "[The Most Holy Name of Jesus]": { "m":  8, "d":  7 }, 
  "Ss. Cyriacus, Largus & Smaragdus, Martyrs": { "m":  8, "d":  8 }, 
  "Vigil of St. Laurence": { "m":  8, "d":  9 }, 
  "St. Romanus, Martyr": { "m":  8, "d":  9 }, 
  "St. Laurence, Deacon & Martyr": { "m":  8, "d": 10 }, 
  "Ss. Tiburtius & Susanna, Martyrs": { "m":  8, "d": 11 }, 
  "St. Maximus of Constantinople, Confessor": { "m":  8, "d": 13 }, 
  "Ss. Hippolytus & Cassian, Martyrs": { "m":  8, "d": 13 }, 
  "Vigil of the Assumption": { "m":  8, "d": 14 }, 
  "St. Eusebius, Priest & Confessor": { "m":  8, "d": 14 }, 
  "The Assumption of The B.V.M.": { "m":  8, "d": 15 }, 
  "St. Joachim, Father of the B.V.M.": { "m":  8, "d": 16 }, 
  "Day II within the Octave of the Assumption": { "m":  8, "d": 16 }, 
  "Day III within the Octave of the Assumption": { "m":  8, "d": 17 }, 
  "Octave of St. Laurence": { "m":  8, "d": 17 }, 
  "Day IV within the Octave of the Assumption": { "m":  8, "d": 18 }, 
  "St. Helen, Empress": { "m":  8, "d": 18 }, 
  "St. Agapitus, Martyr": { "m":  8, "d": 18 }, 
  "Day V within the Octave of the Assumption": { "m":  8, "d": 19 }, 
  "Day VI within the Octave of the Assumption": { "m":  8, "d": 20 }, 
  "Day VII within the Octave of the Assumption": { "m":  8, "d": 21 }, 
  "Octave of the Assumption": { "m":  8, "d": 22 }, 
  "Ss. Timothy (Bishop),Hippolytus & Symphorian, Martyrs": { "m":  8, "d": 22 }, 
  "Vigil of St. Bartholomew": { "m":  8, "d": 23 }, 
  "St. Bartholomew, Apostle": { "m":  8, "d": 24 }, 
  "St. Hilda of Whitby, Virgin": { "m":  8, "d": 25 }, 
  "St. Zephyrinus, Bishop & Martyr": { "m":  8, "d": 26 }, 
  "St. Augustine of Hippo, Bishop, Confessor & Doctor": { "m":  8, "d": 28 }, 
  "St. Hermes, Martyr": { "m":  8, "d": 28 }, 
  "Beheading of St. John Baptist": { "m":  8, "d": 29 }, 
  "St. Sabina, Martyr": { "m":  8, "d": 29 }, 
  "Ss. Felix & Adauctus, Martyrs": { "m":  8, "d": 30 }, 
  "St. Aidan of Lindisfarne, Bishop & Confessor": { "m":  8, "d": 31 }, 
  "St. Giles, Abbot": { "m":  9, "d":  1 }, 
  "Twelve Holy Brothers, Martyrs": { "m":  9, "d":  1 }, 
  "St. Stephen of Hungary, King & Confessor": { "m":  9, "d":  2 }, 
  "St. Gorazde of Prague, Bishop & Martyr": { "m":  9, "d":  4 }, 
  "The Nativity of The B.V.M.": { "m":  9, "d":  8 }, 
  "St. Hadrian, Martyr": { "m":  9, "d":  8 }, 
  "St. Gorgonius, Martyr": { "m":  9, "d":  9 }, 
  "Ss. Protus & Hyacinth, Martyrs": { "m":  9, "d": 11 }, 
  "Exaltation of the Holy Cross": { "m":  9, "d": 14 }, 
  "Seven Sorrows of the B.V.M.": { "m":  9, "d": 15 }, 
  "St. Nicomedes, Martyr": { "m":  9, "d": 15 }, 
  "Ss. Cornelius & Cyprian, Bishops & Martyrs": { "m":  9, "d": 16 }, 
  "Ss. Euphemia, Lucy & Geminian, Martyrs": { "m":  9, "d": 16 }, 
  "St. Januarius & companions, Martyrs": { "m":  9, "d": 19 }, 
  "St. Theodore of Canterbury, Bishop & Confessor": { "m":  9, "d": 19 }, 
  "St. Eustace & companions, Martyrs": { "m":  9, "d": 20 }, 
  "St. Matthew, Apostle & Evangelist": { "m":  9, "d": 21 }, 
  "St. Maurice & companions, Martyrs": { "m":  9, "d": 22 }, 
  "St. Linus, Bishop & Martyr": { "m":  9, "d": 23 }, 
  "St. Thecla, Virgin & Martyr": { "m":  9, "d": 23 }, 
  "Ss. Peter & Juvenaly, Martyrs": { "m":  9, "d": 24 }, 
  "Ss. Cyprian & Justina, Martyrs": { "m":  9, "d": 26 }, 
  "Ss. Cosmas & Damian, Martyrs": { "m":  9, "d": 27 }, 
  "St. Wenceslaus, Duke, Martyr": { "m":  9, "d": 28 }, 
  "Dedication of St. Michael the Archangel": { "m":  9, "d": 29 }, 
  "St. Jerome, Priest, Confessor & Doctor": { "m":  9, "d": 30 }, 
  "St. Gregory of Armenia, Bishop & Confessor": { "m":  9, "d": 30 }, 
  "St. Remigius, Bishop & Confessor": { "m": 10, "d":  1 }, 
  "Holy Guardian Angels": { "m": 10, "d":  2 }, 
  "St. Placidus & companions, Martyrs": { "m": 10, "d":  5 }, 
  "St. Mark of Rome, Bishop & Confessor": { "m": 10, "d":  7 }, 
  "Ss. Sergius, Bacchus, Marcellus & Apuleius, Martyrs": { "m": 10, "d":  7 }, 
  "Ss. Denys, Rusticus & Eleutherius, Martyrs": { "m": 10, "d":  9 }, 
  "Motherhood of the B.V.M.": { "m": 10, "d": 11 }, 
  "St. Wilfrid, Bishop & Confessor": { "m": 10, "d": 12 }, 
  "St. Edward, King & Confessor": { "m": 10, "d": 13 }, 
  "St. Callistus, Bishop & Martyr": { "m": 10, "d": 14 }, 
  "Our Lady of Walsingham": { "m": 10, "d": 15 }, 
  "St. Luke, Evangelist": { "m": 10, "d": 18 }, 
  "St. Frideswide, Virgin": { "m": 10, "d": 19 }, 
  "St. Hilarion, Abbot": { "m": 10, "d": 21 }, 
  "Ss. Ursula & companions, Martyrs": { "m": 10, "d": 21 }, 
  "St. Raphael the Archangel": { "m": 10, "d": 24 }, 
  "Ss. Chrysanthus & Daria, Martyrs": { "m": 10, "d": 25 }, 
  "St. Evaristus, Bishop & Martyr": { "m": 10, "d": 26 }, 
  "Vigil of Ss. Simon & Jude": { "m": 10, "d": 27 }, 
  "Ss. Simon & Jude, Apostles": { "m": 10, "d": 28 }, 
  "Vigil of All Saints": { "m": 10, "d": 31 }, 
  "The Feast of All Saints": { "m": 11, "d":  1 }, 
  "Commemoration of All the Faithful Departed": { "m": 11, "d":  2 }, 
  "(All Souls’ Day)": { "m": 11, "d":  2 }, 
  "Day II within the Octave of All Saints": { "m": 11, "d":  2 }, 
  "Day III within the Octave of All Saints": { "m": 11, "d":  3 }, 
  "St. Winifred, Virgin & Martyr": { "m": 11, "d":  3 }, 
  "Day IV within the Octave of All Saints": { "m": 11, "d":  4 }, 
  "Ss. Vitalis & Agricola, Martyrs": { "m": 11, "d":  4 }, 
  "Day V within the Octave of All Saints": { "m": 11, "d":  5 }, 
  "St. Elizabeth, Mother of St. John Baptist": { "m": 11, "d":  5 }, 
  "Day VI within the Octave of All Saints": { "m": 11, "d":  6 }, 
  "Day VII within the Octave of All Saints": { "m": 11, "d":  7 }, 
  "St. Willibrord, Bishop & Confessor": { "m": 11, "d":  7 }, 
  "Octave Day of All Saints": { "m": 11, "d":  8 }, 
  "Four Crowned Martyrs": { "m": 11, "d":  8 }, 
  "Patriarchs & Prophets": { "m": 11, "d":  8 }, 
  "Dedication of The Basilica of St. Saviour": { "m": 11, "d":  9 }, 
  "St. Theodore Tyro, Martyr": { "m": 11, "d":  9 }, 
  "Ss. Tryphon, Respicius & Nympha, Martyrs": { "m": 11, "d": 10 }, 
  "St. Martin of Tours, Bishop & Confessor": { "m": 11, "d": 11 }, 
  "St. Mennas, Martyr": { "m": 11, "d": 11 }, 
  "St. Theodore the Studite, Abbot": { "m": 11, "d": 11 }, 
  "St. Martin I, Bishop & Martyr": { "m": 11, "d": 12 }, 
  "St. Britius of Tours, Bishop & Confessor": { "m": 11, "d": 13 }, 
  "St. Gregory Palamas, Bishop & Confessor": { "m": 11, "d": 14 }, 
  "St. Gregory the Wonder-worker, Bishop & Confessor": { "m": 11, "d": 17 }, 
  "St. Gregory of Tours, Bishop & Confessor": { "m": 11, "d": 17 }, 
  "Dedication of the Basilica of the Holy Apostles Peter & Paul": { "m": 11, "d": 18 }, 
  "St. Pontianus, Bishop & Martyr": { "m": 11, "d": 19 }, 
  "St. Edmund, King & Martyr": { "m": 11, "d": 20 }, 
  "The Presentation of the B.V.M.": { "m": 11, "d": 21 }, 
  "St. Gelasius, Bishop & Confessor": { "m": 11, "d": 21 }, 
  "St. Columbanus, Abbot": { "m": 11, "d": 21 }, 
  "St. Cecilia, Virgin & Martyr": { "m": 11, "d": 22 }, 
  "St. Clement, Bishop & Martyr": { "m": 11, "d": 23 }, 
  "St. Felicitas, Martyr": { "m": 11, "d": 23 }, 
  "St. Chrysogonus, Martyr": { "m": 11, "d": 24 }, 
  "St. Catherine of Alexandria, Virgin & Martyr": { "m": 11, "d": 25 }, 
  "St. Peter of Alexandria, Bishop & Martyr": { "m": 11, "d": 26 }, 
  "Vigil of St. Andrew": { "m": 11, "d": 29 }, 
  "St. Saturninus, Bishop & Martyr": { "m": 11, "d": 29 }, 
  "St. Andrew, Apostle": { "m": 11, "d": 30 }, 
  "St. Peter Chrysologus, Bishop, Confessor & Doctor": { "m": 12, "d":  2 }, 
  "St. Bibiana, Virgin & Martyr": { "m": 12, "d":  2 }, 
  "St. Barbara, Virgin & Martyr": { "m": 12, "d":  4 }, 
  "St. Sabbas of Judæa, Abbot": { "m": 12, "d":  5 }, 
  "St. Nicholas, Bishop & Confessor": { "m": 12, "d":  6 }, 
  "St. Ambrose of Milan, Bishop, Confessor & Doctor": { "m": 12, "d":  7 }, 
  "The Conception of the B.V.M.": { "m": 12, "d":  8 }, 
  "Day II within Conception Octave": { "m": 12, "d":  9 }, 
  "Day III within Conception Octave": { "m": 12, "d": 10 }, 
  "St. Melchiades, Bishop & Martyr": { "m": 12, "d": 10 }, 
  "St. Damasus, Bishop & Confessor": { "m": 12, "d": 11 }, 
  "Day IV within Conception Octave": { "m": 12, "d": 11 }, 
  "Day V within Conception Octave": { "m": 12, "d": 12 }, 
  "St. Lucy, Virgin & Martyr": { "m": 12, "d": 13 }, 
  "Day VI within Conception Octave": { "m": 12, "d": 13 }, 
  "St. Herman of Alaska, Priest & Confessor": { "m": 12, "d": 13 }, 
  "Day VII within Conception Octave": { "m": 12, "d": 14 }, 
  "Octave of the Conception of the B.V.M.": { "m": 12, "d": 15 }, 
  "St. Eusebius of Vercelli, Bishop & Martyr": { "m": 12, "d": 16 }, 
  "Expectation of the B.V.M.": { "m": 12, "d": 18 }, 
  "St. Thomas, Apostle": { "m": 12, "d": 21 }, 
  "Vigil of the Nativity of the Lord": { "m": 12, "d": 24 }, 
  "The Nativity of Our Lord": { "m": 12, "d": 25 }, 
  "St. Anastasia, Virgin & Martyr": { "m": 12, "d": 25 }, 
  "St. Stephen, Protomartyr": { "m": 12, "d": 26 }, 
  "Day II within the Nativity Octave": { "m": 12, "d": 26 }, 
  "St. John, Apostle & Evangelist": { "m": 12, "d": 27 }, 
  "Day III within the Nativity Octave": { "m": 12, "d": 27 }, 
  "The Holy Innocents, Martyrs": { "m": 12, "d": 28 }, 
  "Day IV within the Nativity Octave": { "m": 12, "d": 28 }, 
  "Day V within the Nativity Octave": { "m": 12, "d": 29 }, 
  "Day VI within the Nativity Octave": { "m": 12, "d": 30 }, 
  "Day VII within the Nativity Octave": { "m": 12, "d": 31 }, 
  "St. Sylvester, Bishop & Confessor": { "m": 12, "d": 31 }
}

var meta = {
  "The Circumcision of Our Lord": { "class": "D2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Most Holy Name of Jesus": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of St. Stephen": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of St. John, Apostle & Evangelist": { "class": "S", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Octave Day of the Holy Innocents": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Titus, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Vigil of the Epiphany": { "class": "V2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Telesphorus of Rome, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Epiphany of Our Lord": { "class": "D1", "octave": "2", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Holy Family: Mary, Jesus & Joseph": { "class": "Gd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "I Sunday after the Epiphany": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Paul the First Hermit": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Hyginus of Rome, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of the Epiphany": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Benedict Biscop, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of the Epiphany": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Hilary, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Felix of Nola, Priest & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "II Sunday after the Epiphany": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Maurus, Abbot": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Marcellus of Rome, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Anthony, Abbot": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Chair of St. Peter in Rome": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Paul": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Prisca of Rome, Virgin Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Marius, Martha, Audifax, & Abachum, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Mark of Ephesus, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Fabian (Bishop) & Sebastian, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Agnes of Rome, Virgin & Martyr": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "III Sunday after the Epiphany": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Ss. Vincent (Deacon) & Anastasius, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Emerentiana, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Timothy, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Conversion Of St. Paul The Apostle": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Peter": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Polycarp of Smyrna, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John Chrysostom, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Second Feast of St. Agnes, Virgin Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "IV Sunday after the Epiphany": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Martina, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Ignatius of Antioch, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Bridget of Ireland, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Purification of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "St. Blaise, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The New Martyrs of Russia": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Joseph of Aleppo, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "V Sunday after the Epiphany": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Agatha, Virgin & Martyr, Abbot": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Photius, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Dorothy, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Romuald, Abbot": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Cyril of Alexandria, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Apollonia of Alexandria, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Scholastica, Virgin": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday of Septuagesima": { "class": "Sd2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Gregory II, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Valentine, Priest & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Faustinus & Jovita, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Simeon of Jerusalem, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday of Sexagesima": { "class": "Sd2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Chair of St. Peter at Antioch": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Paul": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of Feria": { "class": "F3", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. Matthias": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Matthias, Apostle": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Walburga of Heidenheim, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday of Quinquagesima": { "class": "Sd2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Raphael of Brooklyn, Bishop & Confessor": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Alexander of Alexandria, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ash Wednesday": { "class": "F1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. David of Wales, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Ash Wednesday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Chad, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday after Ash Wednesday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday after Ash Wednesday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "I Sunday in Lent": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday after Lent I": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Perpetua & Felicitas, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday after Lent I": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Wednesday in Lent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Lent I": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory of Nyssa, Bishop, Confessor & Doctor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Friday in Lent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Forty Holy Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Saturday in Lent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "II Sunday in Lent": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Gregory the Great, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Monday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Patrick, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Joseph of Arimathea, C.": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday after Lent II": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Cyril of Jerusalem, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Edward, King & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Joseph, Spouse of the B.V.M.": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "III Sunday in Lent": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Cuthbert, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Monday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Benedict, Abbot": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday after Lent III": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gabriel the Archangel": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Annunciation of the B.V.M.": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "IV Sunday in Lent": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John Damascene, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John Climacus, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Innocent of Alaska, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday after Lent IV": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Sunday of the Passion": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Isidore of Seville, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Tikhon of Moscow, Bishop & Confessor": { "class": "D1", "octave": "C", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Friday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Our Lady of Sorrows": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday after Passion Sunday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Palm Sunday": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday in Holy Week": { "class": "F1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday in Holy Week": { "class": "F1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Leo the Great, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday in Holy Week": { "class": "F1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday of the Lord’s Supper": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Hermengild, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday of the Preparation (Good Friday)": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Justin, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Tiburtius, Valerian & Maximus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Holy Saturday": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Sunday of the Resurrection": { "class": "D1", "octave": "1", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday in the Octave of Easter": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Anicetus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday in the Octave of Easter": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Wednesday in the Octave of Easter": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday in the Octave of Easter": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday in the Octave of Easter": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday in the Octave of Easter (Sabbato in Albis)": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Soter & Caius, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. George, Martyr": { "class": "D1", "octave": "C", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Octave of Easter (Dominica in Albis; Low Sunday)": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Mark, Evangelist": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Cletus & Marcellinus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Vitalis, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of St. George": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "II Sunday after Easter": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Octave Day of St. George": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Philip & James, Apostles": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Athanasius, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Finding of the Holy Cross": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Solemnity of St. Joseph, Spouse of the B.V.M.": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Alexander (Bishop), Eventius, Theodulus (Martyrs) & Juvenalis (Bishop & Confessor)": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Monica, Widow": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John before the Latin Gate": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "III Sunday after Easter": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Alexis Toth, Priest & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Apparition of St. Michael the Archangel": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory Nazianzen, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Gordian & Epimachus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Pachomius, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Nereus, Achilles, Domitilla & Pancras, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "IV Sunday after Easter": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Boniface of Tarsus, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Venantius, Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Pudentiana, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Dunstan of Canterbury, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "V Sunday after Easter": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Constantine, Emperor & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Rogation Monday": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Rogation Tuesday": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Vigil of the Ascension": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Vincent of Lerins, Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Ascension of Our Lord": { "class": "D1", "octave": "3", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Urban, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Augustine of Canterbury, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Eleutherius, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Bede the Venerable, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John I, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Commemoration of Ascension Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Felix I, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Petronilla, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Octave of the Ascension": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Friday after the Octave of the Ascension": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Marcellinus, Peter & Erasmus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Vigil of Pentecost": { "class": "V1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Pentecost Sunday": { "class": "D1", "octave": "1", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Monday within the Octave of Pentecost": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Boniface, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Tuesday within the Octave of Pentecost": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Wednesday in Pentecost": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Thursday within the Octave of Pentecost": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Friday in Pentecost": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Columba of Iona, Abbot": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Primus & Felician, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Saturday in Pentecost": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Margaret of Scotland, Queen & Widow": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Feast of the Most Holy Trinity": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "I Sunday after Pentecost": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Barnabas, Apostle": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Basilides, Cyrinus, Nabor & Nazarius, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Basil the Great, Bishop, Confessor & Doctor": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Feast of the Most Holy Body of Christ": { "class": "D1", "octave": "2", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Ss. Vitus, Modestus & Crescentia, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Sudday within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Ephrem the Syrian, Deacon, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Mark & Marcellianus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Gervase & Protase, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Silverius, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Translation of St. Edward, King & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of Corpus Christi": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of Corpus Christi": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Alban, Protomartyr of England": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Paulinus, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. John the Baptist": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Etheldreda, Queen & Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Nativity of St. John the Baptist": { "class": "D1", "octave": "C", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "III Sunday after Pentecost [II Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. John & Paul, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Irenæus of Lyons, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Peter & Paul, Apostles": { "class": "D1", "octave": "C", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Day VI within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Paul, Apostle": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Peter, Apostle": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of St. John Baptist": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of the Most Sacred Heart of Jesus": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "y" }, 
  "Octave of St. John Baptist": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Most Precious Blood of Our Lord Jesus Christ": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "y" }, 
  "Visitation of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "IV Sunday after Pentecost [III Trinity]": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John of San Francisco, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Processus & Martinian, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Leo II, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Octave of Ss. Peter & Paul": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Cyril and Methodius, Bishops & Confessors": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "V Sunday after Pentecost [IV Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "The Seven Holy Brothers, with Ss. Rufina & Secunda, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Joseph of Damascus (Priest) & his companions, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Pius I, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Nabor & Felix, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Anacletus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Vladimir of Kiev, King & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Henry, Emperor & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "VI Sunday after Pentecost [V Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Our Lady of Einsiedeln": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Alexius, Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Sergius of Radonezh, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Symphorosa & her seven sons, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Seraphim of Sarov, Priest & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Elias the Prophet": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Margaret of Antioch, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Praxedes, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Mary Magdalene, Penitent": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "VII Sunday after Pentecost [VI Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. John Cassian, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Apollinaris of Ravenna, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Liborius, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. James": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Christina, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. James, Apostle": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Christopher, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Anne, Mother of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Pantaleon, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Nazarius, Celsus, Martyrs; St. Victor, Bishop & Martyr; & Innocent, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Martha of Bethany, Virgin": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Felix II (Bishop), Simplicius, Faustinus & Beatrice, Martryrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "VIII Sunday after Pentecost [VII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Ss. Abdon & Sennen, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Chains of St. Peter, Apostle": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of St. Paul, Apostle": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Holy Maccabees, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Stephen, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Finding of St. Stephen, Protomartyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Dedication of Our Lady of the Snows": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Oswald, King & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Transfiguration of Our Lord Jesus Christ": { "class": "D2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "IX Sunday after Pentecost [VIII Trinity]": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Sixtus II (Bishop & Martyr), Felicissimus & Agapitus (Deacons), Martyrs": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Donatus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "[The Most Holy Name of Jesus]": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "y" }, 
  "Ss. Cyriacus, Largus & Smaragdus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. Laurence": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Romanus, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Laurence, Deacon & Martyr": { "class": "D2", "octave": "S", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Tiburtius & Susanna, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "X Sunday after Pentecost [IX Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Maximus of Constantinople, Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Hippolytus & Cassian, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of the Assumption": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Eusebius, Priest & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Assumption of The B.V.M.": { "class": "D1", "octave": "C", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Joachim, Father of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day II within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of St. Laurence": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Helen, Empress": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Agapitus, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XI Sunday after Pentecost [X Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of the Assumption": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of the Assumption": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Timothy (Bishop),Hippolytus & Symphorian, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. Bartholomew": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Bartholomew, Apostle": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Hilda of Whitby, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Zephyrinus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XII Sunday after Pentecost [XI Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Augustine of Hippo, Bishop, Confessor & Doctor": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Hermes, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Beheading of St. John Baptist": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Sabina, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Felix & Adauctus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Aidan of Lindisfarne, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Giles, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Twelve Holy Brothers, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Stephen of Hungary, King & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XIII Sunday after Pentecost [XII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Gorazde of Prague, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Nativity of The B.V.M.": { "class": "D2", "octave": "S", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "St. Hadrian, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gorgonius, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XIV Sunday after Pentecost [XIII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Ss. Protus & Hyacinth, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Exaltation of the Holy Cross": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Seven Sorrows of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Nicomedes, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Cornelius & Cyprian, Bishops & Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Euphemia, Lucy & Geminian, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XV Sunday after Pentecost [XIV Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Januarius & companions, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Theodore of Canterbury, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Wednesday in September": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Eustace & companions, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Matthew, Apostle & Evangelist": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Friday in September": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "y" }, 
  "St. Maurice & companions, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Saturday in September": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Linus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Thecla, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XVI Sunday after Pentecost [XV Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Ss. Peter & Juvenaly, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Cyprian & Justina, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Cosmas & Damian, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Wenceslaus, Duke, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Dedication of St. Michael the Archangel": { "class": "D1", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Jerome, Priest, Confessor & Doctor": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory of Armenia, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XVII Sunday after Pentecost [XVI Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Remigius, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Holy Guardian Angels": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Placidus & companions, Martyrs": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Mark of Rome, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Sergius, Bacchus, Marcellus & Apuleius, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XVIII Sunday after Pentecost [XVII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "XXIV and Last Sunday after Pentecost [Sunday Next Before Advent]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Ss. Denys, Rusticus & Eleutherius, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Motherhood of the B.V.M.": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Wilfrid, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Edward, King & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Callistus, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XIX Sunday after Pentecost [XVIII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Our Lady of Walsingham": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Luke, Evangelist": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Frideswide, Virgin": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Saturday Office of the B.V.M.": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Hilarion, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Ursula & companions, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XX Sunday after Pentecost [XIX Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Raphael the Archangel": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Chrysanthus & Daria, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Evaristus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of Ss. Simon & Jude": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Simon & Jude, Apostles": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Feast of Our Lord Jesus Christ the King": { "class": "D1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "XXI Sunday after Pentecost [XX Trinity]": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of All Saints": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Feast of All Saints": { "class": "D1", "octave": "C", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Commemoration of All the Faithful Departed": { "class": "D", "octave": "N", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Day II within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Winifred, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Vitalis & Agricola, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XXII Sunday after Pentecost [XXI Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day V within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Elizabeth, Mother of St. John Baptist": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Octave of All Saints": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Willibrord, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of All Saints": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Four Crowned Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Patriarchs & Prophets": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Dedication of The Basilica of St. Saviour": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Theodore Tyro, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Tryphon, Respicius & Nympha, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Martin of Tours, Bishop & Confessor": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Mennas, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Theodore the Studite, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XXIII Sunday after Pentecost [XXII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Martin I, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Britius of Tours, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory Palamas, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory the Wonder-worker, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Gregory of Tours, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Dedication of the Basilica of the Holy Apostles Peter & Paul": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "VI Sunday after Epiphany (Resumed) [XXIII Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Pontianus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Edmund, King & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Presentation of the B.V.M.": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "St. Gelasius, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Columbanus, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Cecilia, Virgin & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Clement, Bishop & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Felicitas, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Chrysogonus, Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Catherine of Alexandria, Virgin & Martyr": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "XXIV & Last Sunday after Pentecost": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Peter of Alexandria, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of St. Andrew": { "class": "V", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Saturninus, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Andrew, Apostle": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Peter Chrysologus, Bishop, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Bibiana, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "I Sunday in Advent": { "class": "Sd1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Barbara, Virgin & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Sabbas of Judæa, Abbot": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Nicholas, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Commemoration of Advent Feria": { "class": "F3", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Ambrose of Milan, Bishop, Confessor & Doctor": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Conception of the B.V.M.": { "class": "D1", "octave": "C", "obligation": "n", "devotion": "y", "bracket": "n" }, 
  "Day II within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "II Sunday in Advent": { "class": "Sd2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Day III within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Melchiades, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Damasus, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Lucy, Virgin & Martyr": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Herman of Alaska, Priest & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within Conception Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of the Conception of the B.V.M.": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Eusebius of Vercelli, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "III Sunday in Advent": { "class": "Sd2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Expectation of the B.V.M.": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Wednesday in Advent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Thomas, Apostle": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Friday in Advent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ember Saturday in Advent": { "class": "F2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Vigil of the Nativity of the Lord": { "class": "V1", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "IV Sunday in Advent": { "class": "Sd2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Nativity of Our Lord": { "class": "D1", "octave": "3", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Anastasia, Virgin & Martyr": { "class": "Comm", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Stephen, Protomartyr": { "class": "D2", "octave": "S", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day II within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. John, Apostle & Evangelist": { "class": "D2", "octave": "S", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Holy Innocents, Martyrs": { "class": "D2", "octave": "S", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day IV within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day V within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VI within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day VII within the Nativity Octave": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Sunday within the Octave of the Nativity": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Sylvester, Bishop & Confessor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Circumcision of Our Lord": { "class": "D2", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Most Holy Name of Jesus": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of St. Stephen": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave Day of St. John, Apostle & Evangelist": { "class": "S", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Octave Day of the Holy Innocents": { "class": "S", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Titus, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Vigil of the Epiphany": { "class": "V2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Telesphorus of Rome, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "The Epiphany of Our Lord": { "class": "D1", "octave": "2", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "Feast of the Most Sacred Heart of Jesus": { "class": "D1", "octave": "S", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Most Precious Blood of Our Lord Jesus Christ": { "class": "D2", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Octave of St. John Baptist": { "class": "Gd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Day III within the Octave of Ss. Peter & Paul": { "class": "Sd", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Vitus, Modestus & Crescentia, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "II Sunday after Pentecost [I Trinity]": { "class": "Sd", "octave": "N", "obligation": "y", "devotion": "n", "bracket": "n" }, 
  "St. Ephrem the Syrian, Deacon, Confessor & Doctor": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Mark & Marcellianus, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Ss. Gervase & Protase, Martyrs": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Silverius, Bishop & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "Translation of St. Edward, King & Martyr": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Alban, Protomartyr of England": { "class": "D", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }, 
  "St. Paulinus, Bishop & Confessor": { "class": "M", "octave": "N", "obligation": "n", "devotion": "n", "bracket": "n" }
}
