// Headless verification harness (Node, no browser).
//
//   node tools/verify.mjs [year]
//
// 1. Loads the feast database (kalendar_data.js) into globals exactly as the
//    browser does, then runs the REAL engine (kalendar.js).
// 2. Generates the engine's publication CSV for the year and writes it to
//    data/<year>/kalendar_<year>_engine.csv.
// 3. Diffs it against the PDF-derived reference CSV and writes a human-readable
//    data/<year>/diff_report.md (report-only; the engine is never modified).
// 4. Runs structural unit assertions on the new column generators.
//
// Exit code is non-zero only if a STRUCTURAL assertion fails. Feast/rank
// differences vs the reference are reported, not failed, per project decision.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const REPO = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const YEAR = parseInt(process.argv[2] || '2027', 10);

// --- 1. Load the feast database into globals (as kalendar.html does) ----------
const dataSrc = fs.readFileSync(path.join(REPO, 'kalendar_data.js'), 'utf8');
const ctx = {};
vm.createContext(ctx);
vm.runInContext(dataSrc, ctx);
for (const name of ['moveable', 'fixed', 'meta', 'ranknames', 'months', 'daysofweek']) {
  globalThis[name] = ctx[name];
}
globalThis.alert = (msg) => console.warn('[engine alert]', msg);

// --- 2. Import the real engine + publish modules -----------------------------
const Kalendar = (await import('../kalendar.js')).default;
const {buildPublication} = await import('../publish_model.js');
const {getDayLetter, getSundayLetter, getEpact, formatRank} = await import('../publish_columns.js');
const {toCsv} = await import('../csv_export.js');

const epactTable = JSON.parse(fs.readFileSync(path.join(REPO, 'data', 'epacts.json'), 'utf8'));
const monthNotes = JSON.parse(fs.readFileSync(path.join(REPO, 'data', 'monthnotes.json'), 'utf8'));

const k = new Kalendar(YEAR);
const ydir = path.join(REPO, 'data', String(YEAR));
fs.mkdirSync(ydir, {recursive: true});

// --- engine CSV ---------------------------------------------------------------
const engineCsv = toCsv(YEAR, k, epactTable, monthNotes);
fs.writeFileSync(path.join(ydir, `kalendar_${YEAR}_engine.csv`), engineCsv);

// --- 3. Diff engine vs reference ---------------------------------------------
function parseCsv(text) {
  // minimal CSV parser (handles quoted fields with commas / quotes)
  const rows = [];
  for (const line of text.split(/\r?\n/)) {
    if (line === '') continue;
    const cells = [];
    let cur = '', inq = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (inq) {
        if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
        else if (ch === '"') inq = false;
        else cur += ch;
      } else if (ch === '"') inq = true;
      else if (ch === ',') { cells.push(cur); cur = ''; }
      else cur += ch;
    }
    cells.push(cur);
    rows.push(cells);
  }
  return rows;
}

// Group rows by (month, day) with day forward-filled; collect "feast | rank".
function groupByDay(rows) {
  const out = new Map();
  let curDay = null, curMonth = null;
  for (let i = 1; i < rows.length; i++) {
    const [epact, dl, day, feast, rank, month] = rows[i];
    if (month) curMonth = month;
    if (day) curDay = day;
    const key = `${curMonth}-${String(curDay).padStart(2, '0')}`;
    if (!out.has(key)) out.set(key, []);
    out.get(key).push(`${feast} | ${rank}`);
  }
  return out;
}

const refPath = path.join(ydir, `kalendar_${YEAR}_reference.csv`);
let diffReport = `# Diff report: engine vs reference PDF — ${YEAR}\n\n`;
diffReport += `Generated by tools/verify.mjs. Report-only; the engine is NOT modified.\n\n`;

if (fs.existsSync(refPath)) {
  const ref = groupByDay(parseCsv(fs.readFileSync(refPath, 'utf8')));
  const eng = groupByDay(parseCsv(engineCsv));
  const keys = [...new Set([...ref.keys(), ...eng.keys()])].sort();
  let diffCount = 0;
  diffReport += `| Date (M-D) | Reference (PDF) | Engine |\n|---|---|---|\n`;
  for (const key of keys) {
    const r = (ref.get(key) || []).join('<br>');
    const e = (eng.get(key) || []).join('<br>');
    if (r !== e) {
      diffCount++;
      diffReport += `| ${key} | ${r || '—'} | ${e || '—'} |\n`;
    }
  }
  diffReport = diffReport.replace('Report-only',
    `**${diffCount}** day(s) differ out of ${keys.length}.\n\nReport-only`);
  console.log(`Diff: ${diffCount} of ${keys.length} days differ (see diff_report.md)`);
} else {
  diffReport += `_No reference CSV found at ${path.relative(REPO, refPath)}._\n`;
  console.log('No reference CSV found; skipping diff.');
}
fs.writeFileSync(path.join(ydir, 'diff_report.md'), diffReport);

// --- 4. Structural assertions ------------------------------------------------
let failures = 0;
function check(name, got, want) {
  const ok = got === want;
  if (!ok) { failures++; console.log(`  FAIL ${name}: got ${JSON.stringify(got)} want ${JSON.stringify(want)}`); }
  else console.log(`  ok   ${name}`);
}
console.log('\nStructural assertions:');
check('getDayLetter(1,1)=A', getDayLetter(1, 1), 'A');
check('getDayLetter(1,8)=A', getDayLetter(1, 8), 'A');
check('getDayLetter(1,3)=c', getDayLetter(1, 3), 'c');
check('getDayLetter(2,1)=d', getDayLetter(2, 1), 'd');
check('getSundayLetter(2027)=C', getSundayLetter(2027), 'C');
check('getSundayLetter(2026)=D', getSundayLetter(2026), 'D');
check('formatRank D1/O2', formatRank({office: 'D1', octave: '2'}), 'D1, O2');
check('formatRank D2/N', formatRank({office: 'D2', octave: 'N'}), 'D2');
check('getEpact(1,1)=*', getEpact(epactTable, 1, 1), '*');
check('getEpact(1,6)=25 xxv', getEpact(epactTable, 1, 6), '25 xxv');
check('getEpact(1,30)=i', getEpact(epactTable, 1, 30), 'i');
check('monthNotes has Jan note', (monthNotes['1'] || []).length > 0, true);
check('monthNotes May empty', (monthNotes['5'] || []).length, 0);

// sanity: every day of the year has at least the expected structure
const months = buildPublication(YEAR, k, epactTable, monthNotes);
const totalDays = months.reduce((a, m) => a + m.days.length, 0);
check('day count', totalDays, ((YEAR % 4 === 0 && (YEAR % 100 !== 0 || YEAR % 400 === 0)) ? 366 : 365));

// --- master (perpetual) Kalendar: fixed feasts only ---------------------------
console.log('\nMaster Kalendar assertions:');
const km = new Kalendar(2001, true);
const masterMonths = buildPublication(null, km, epactTable, monthNotes);
const allFeasts = masterMonths.flatMap(m => m.days.flatMap(d => d.celebrations.map(c => c.feast)));
const has = (re) => allFeasts.some(f => re.test(f));
check('master: Feb has 28 days', masterMonths[1].days.length, 28);
check('master: includes Octave Day of St. Stephen', has(/Octave Day of St\. Stephen/), true);
check('master: includes Day II within the Octave of the Epiphany', has(/Day II within the Octave of the Epiphany/), true);
check('master: EXCLUDES Saturday Office of the B.V.M.', has(/Saturday Office of the B\.V\.M\./), false);
check('master: EXCLUDES Sunday within the Octave', has(/Sunday within the Octave/), false);
check('master: EXCLUDES Sunday after the Epiphany', has(/Sunday after the Epiphany/), false);
check('master: dow is -1 (no weekday)', masterMonths[0].days[0].dow, -1);

console.log(`\n${failures === 0 ? 'ALL STRUCTURAL CHECKS PASSED' : failures + ' STRUCTURAL CHECK(S) FAILED'}`);
process.exit(failures === 0 ? 0 : 1);
